name: Deploy to GCloud Functions on merge
"on":
  push:
    branches:
      - main
jobs:
  functions_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: siejmy
          service_account_key: "${{ secrets.GCLOUD_SERVICE_ACCOUNT_SIEJMY }}"
          export_default_credentials: true
      - run: ./functions/deploy.sh
