name: Deploy to Firebase Functions on merge
"on":
  push:
    branches:
      - main
jobs:
  functions_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - run: npm install firebase-tools
      - run: npm --prefix="./functions" install
      - run: npx firebase --token "${{ secrets.FIREBASE_TOKEN }}" deploy --only functions
      - run: |
        curl -s \
          --form-string "token=${{ secrets.PUSHOVER_APP_KEY }}" \
          --form-string "user=${{ secrets.PUSHOVER_USER_KEY }}" \
          --form-string "message=Siejmyquiz FUNCTIONS deployment done" \
          https://api.pushover.net/1/messages.json
      - name: 'Notify on failure'
        if: ${{ failure() }}
        run: |
        curl -s \
          --form-string "token=${{ secrets.PUSHOVER_APP_KEY }}" \
          --form-string "user=${{ secrets.PUSHOVER_USER_KEY }}" \
          --form-string "message=Siejmyquiz Functions deployment FAILED" \
          https://api.pushover.net/1/messages.json
