name: Deploy to Firebase Functions on merge
"on":
  push:
    branches:
      - main
jobs:
  functions_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - run: npm install firebase-tools
      - run: npm --prefix="./functions" install
      - run: npx firebase --token "${{ secrets.FIREBASE_TOKEN }}" deploy --only functions
